export const FIRST_ROW = [
  {
    code: 'Backquote',
    caseDown: '`',
    caseUp: '~',
    caseDownRu: 'ё',
    caseUpRu: 'Ё',
    capsEn: '`',
    capsRu: 'Ё',
    capsShiftEn: '~',
    capsShiftRu: 'ё',
  },
  {
    code: 'Digit1',
    caseDown: '1',
    caseUp: '!',
    caseDownRu: '1',
    caseUpRu: '!',
    capsEn: '1',
    capsRu: '1',
    capsShiftEn: '!',
    capsShiftRu: '!',
  },
  {
    code: 'Digit2',
    caseDown: '2',
    caseUp: '@',
    caseDownRu: '2',
    caseUpRu: '"',
    capsEn: '2',
    capsRu: '2',
    capsShiftEn: '@',
    capsShiftRu: '"',
  },
  {
    code: 'Digit3',
    caseDown: '3',
    caseUp: '#',
    caseDownRu: '3',
    caseUpRu: '№',
    capsEn: '3',
    capsRu: '3',
    capsShiftEn: '#',
    capsShiftRu: '№',
  },
  {
    code: 'Digit4',
    caseDown: '4',
    caseUp: '$',
    caseDownRu: '4',
    caseUpRu: ';',
    capsEn: '4',
    capsRu: '4',
    capsShiftEn: '$',
    capsShiftRu: ';',
  },
  {
    code: 'Digit5',
    caseDown: '5',
    caseUp: '%',
    caseDownRu: '5',
    caseUpRu: '%',
    capsEn: '5',
    capsRu: '5',
    capsShiftEn: '%',
    capsShiftRu: '%',
  },
  {
    code: 'Digit6',
    caseDown: '6',
    caseUp: '^',
    caseDownRu: '6',
    caseUpRu: ':',
    capsEn: '6',
    capsRu: '6',
    capsShiftEn: '^',
    capsShiftRu: ':',
  },
  {
    code: 'Digit7',
    caseDown: '7',
    caseUp: '&',
    caseDownRu: '7',
    caseUpRu: '?',
    capsEn: '7',
    capsRu: '7',
    capsShiftEn: '&',
    capsShiftRu: '?',
  },
  {
    code: 'Digit8',
    caseDown: '8',
    caseUp: '*',
    caseDownRu: '8',
    caseUpRu: '*',
    capsEn: '8',
    capsRu: '8',
    capsShiftEn: '*',
    capsShiftRu: '*',
  },
  {
    code: 'Digit9',
    caseDown: '9',
    caseUp: '(',
    caseDownRu: '9',
    caseUpRu: '(',
    capsEn: '9',
    capsRu: '9',
    capsShiftEn: '(',
    capsShiftRu: '(',
  },
  {
    code: 'Digit0',
    caseDown: '0',
    caseUp: ')',
    caseDownRu: '0',
    caseUpRu: ')',
    capsEn: '0',
    capsRu: '0',
    capsShiftEn: ')',
    capsShiftRu: ')',
  },
  {
    code: 'Minus',
    caseDown: '-',
    caseUp: '_',
    caseDownRu: '-',
    caseUpRu: '_',
    capsEn: '-',
    capsRu: '-',
    capsShiftEn: '_',
    capsShiftRu: '_',
  },
  {
    code: 'Equal',
    caseDown: '=',
    caseUp: '+',
    caseDownRu: '=',
    caseUpRu: '+',
    capsEn: '=',
    capsRu: '=',
    capsShiftEn: '+',
    capsShiftRu: '+',
  },
  {
    code: 'Backspace',
    caseDown: 'Backspace',
    caseUp: 'Backspace',
    caseDownRu: 'Backspace',
    caseUpRu: 'Backspace',
    capsEn: 'Backspace',
    capsRu: 'Backspace',
    capsShiftEn: 'Backspace',
    capsShiftRu: 'Backspace',
  },
];

export const SECOND_ROW = [
  {
    code: 'Tab',
    caseDown: 'Tab',
    caseUp: 'Tab',
    caseDownRu: 'Tab',
    caseUpRu: 'Tab',
    capsEn: 'Tab',
    capsRu: 'Tab',
    capsShiftEn: 'Tab',
    capsShiftRu: 'Tab',
  },
  {
    code: 'KeyQ',
    caseDown: 'q',
    caseUp: 'Q',
    caseDownRu: 'й',
    caseUpRu: 'Й',
    capsEn: 'Q',
    capsRu: 'Й',
    capsShiftEn: 'q',
    capsShiftRu: 'й',
  },
  {
    code: 'KeyW',
    caseDown: 'w',
    caseUp: 'W',
    caseDownRu: 'ц',
    caseUpRu: 'Ц',
    capsEn: 'W',
    capsRu: 'Ц',
    capsShiftEn: 'w',
    capsShiftRu: 'ц',
  },
  {
    code: 'KeyE',
    caseDown: 'e',
    caseUp: 'E',
    caseDownRu: 'у',
    caseUpRu: 'У',
    capsEn: 'E',
    capsRu: 'У',
    capsShiftEn: 'e',
    capsShiftRu: 'у',
  },
  {
    code: 'KeyR',
    caseDown: 'r',
    caseUp: 'R',
    caseDownRu: 'к',
    caseUpRu: 'К',
    capsEn: 'R',
    capsRu: 'К',
    capsShiftEn: 'r',
    capsShiftRu: 'к',
  },
  {
    code: 'KeyT',
    caseDown: 't',
    caseUp: 'T',
    caseDownRu: 'е',
    caseUpRu: 'Е',
    capsEn: 'T',
    capsRu: 'Е',
    capsShiftEn: 't',
    capsShiftRu: 'е',
  },
  {
    code: 'KeyY',
    caseDown: 'y',
    caseUp: 'Y',
    caseDownRu: 'н',
    caseUpRu: 'Н',
    capsEn: 'Y',
    capsRu: 'Н',
    capsShiftEn: 'y',
    capsShiftRu: 'н',
  },
  {
    code: 'KeyU',
    caseDown: 'u',
    caseUp: 'U',
    caseDownRu: 'г',
    caseUpRu: 'Г',
    capsEn: 'U',
    capsRu: 'Г',
    capsShiftEn: 'u',
    capsShiftRu: 'г',
  },
  {
    code: 'KeyI',
    caseDown: 'i',
    caseUp: 'I',
    caseDownRu: 'ш',
    caseUpRu: 'Ш',
    capsEn: 'I',
    capsRu: 'Ш',
    capsShiftEn: 'i',
    capsShiftRu: 'ш',
  },
  {
    code: 'KeyO',
    caseDown: 'o',
    caseUp: 'O',
    caseDownRu: 'щ',
    caseUpRu: 'Щ',
    capsEn: 'O',
    capsRu: 'Щ',
    capsShiftEn: 'o',
    capsShiftRu: 'щ',
  },
  {
    code: 'KeyP',
    caseDown: 'p',
    caseUp: 'P',
    caseDownRu: 'з',
    caseUpRu: 'З',
    capsEn: 'P',
    capsRu: 'З',
    capsShiftEn: 'p',
    capsShiftRu: 'з',
  },
  {
    code: 'BracketLeft',
    caseDown: '[',
    caseUp: '{',
    caseDownRu: 'х',
    caseUpRu: 'Х',
    capsEn: '[',
    capsRu: 'Х',
    capsShiftEn: '{',
    capsShiftRu: 'х',
  },
  {
    code: 'BracketRight',
    caseDown: ']',
    caseUp: '}',
    caseDownRu: 'ъ',
    caseUpRu: 'Ъ',
    capsEn: ']',
    capsRu: 'Ъ',
    capsShiftEn: '}',
    capsShiftRu: 'ъ',
  },
  {
    code: 'Backslash',
    caseDown: '\\',
    caseUp: '|',
    caseDownRu: '\\',
    caseUpRu: '/',
    capsEn: '\\',
    capsRu: '\\',
    capsShiftEn: '|',
    capsShiftRu: '/',
  },
  {
    code: 'Delete',
    caseDown: 'Del',
    caseUp: 'Del',
    caseDownRu: 'Del',
    caseUpRu: 'Del',
    capsEn: 'Del',
    capsRu: 'Del',
    capsShiftEn: 'Del',
    capsShiftRu: 'Del',
  },
];

export const THIRD_ROW = [
  {
    code: 'CapsLock',
    caseDown: 'CapsLock',
    caseDownRu: 'CapsLock',
    caseUp: 'CapsLock',
    caseUpRu: 'CapsLock',
    capsEn: 'CapsLock',
    capsRu: 'CapsLock',
    capsShiftEn: 'CapsLock',
    capsShiftRu: 'CapsLock',
  },
  {
    code: 'KeyA',
    caseDown: 'a',
    caseUp: 'A',
    caseDownRu: 'ф',
    caseUpRu: 'Ф',
    capsEn: 'A',
    capsRu: 'Ф',
    capsShiftEn: 'a',
    capsShiftRu: 'ф',
  },
  {
    code: 'KeyS',
    caseDown: 's',
    caseUp: 'S',
    caseDownRu: 'ы',
    caseUpRu: 'Ы',
    capsEn: 'S',
    capsRu: 'Ы',
    capsShiftEn: 's',
    capsShiftRu: 'ы',
  },
  {
    code: 'KeyD',
    caseDown: 'd',
    caseUp: 'D',
    caseDownRu: 'в',
    caseUpRu: 'В',
    capsEn: 'D',
    capsRu: 'В',
    capsShiftEn: 'd',
    capsShiftRu: 'в',
  },
  {
    code: 'KeyF',
    caseDown: 'f',
    caseUp: 'F',
    caseDownRu: 'а',
    caseUpRu: 'А',
    capsEn: 'F',
    capsRu: 'А',
    capsShiftEn: 'f',
    capsShiftRu: 'а',
  },
  {
    code: 'KeyG',
    caseDown: 'g',
    caseUp: 'G',
    caseDownRu: 'п',
    caseUpRu: 'П',
    capsEn: 'G',
    capsRu: 'П',
    capsShiftEn: 'g',
    capsShiftRu: 'п',
  },
  {
    code: 'KeyH',
    caseDown: 'h',
    caseUp: 'H',
    caseDownRu: 'р',
    caseUpRu: 'Р',
    capsEn: 'H',
    capsRu: 'Р',
    capsShiftEn: 'h',
    capsShiftRu: 'р',
  },
  {
    code: 'KeyJ',
    caseDown: 'j',
    caseUp: 'J',
    caseDownRu: 'о',
    caseUpRu: 'О',
    capsEn: 'J',
    capsRu: 'О',
    capsShiftEn: 'j',
    capsShiftRu: 'о',
  },
  {
    code: 'KeyK',
    caseDown: 'k',
    caseUp: 'K',
    caseDownRu: 'л',
    caseUpRu: 'Л',
    capsEn: 'K',
    capsRu: 'Л',
    capsShiftEn: 'k',
    capsShiftRu: 'л',
  },
  {
    code: 'KeyL',
    caseDown: 'l',
    caseUp: 'L',
    caseDownRu: 'д',
    caseUpRu: 'Д',
    capsEn: 'L',
    capsRu: 'Д',
    capsShiftEn: 'l',
    capsShiftRu: 'д',
  },
  {
    code: 'Semicolon',
    caseDown: ';',
    caseUp: ':',
    caseDownRu: 'ж',
    caseUpRu: 'Ж',
    capsEn: ';',
    capsRu: 'Ж',
    capsShiftEn: ':',
    capsShiftRu: 'ж',
  },
  {
    code: 'Quote',
    caseDown: "'",
    caseUp: '"',
    caseDownRu: 'э',
    caseUpRu: 'Э',
    capsEn: "'",
    capsRu: 'Э',
    capsShiftEn: '"',
    capsShiftRu: 'э',
  },
  {
    code: 'Enter',
    caseDown: 'Enter',
    caseUp: 'Enter',
    caseDownRu: 'Enter',
    caseUpRu: 'Enter',
    capsEn: 'Enter',
    capsRu: 'Enter',
    capsShiftEn: 'Enter',
    capsShiftRu: 'Enter',
  },
];

export const FOURTH_ROW = [
  {
    code: 'ShiftLeft',
    caseDown: 'Shift',
    caseUp: 'Shift',
    caseDownRu: 'Shift',
    caseUpRu: 'Shift',
    capsEn: 'Shift',
    capsRu: 'Shift',
    capsShiftEn: 'Shift',
    capsShiftRu: 'Shift',
  },
  {
    code: 'KeyZ',
    caseDown: 'z',
    caseUp: 'Z',
    caseDownRu: 'я',
    caseUpRu: 'Я',
    capsEn: 'Z',
    capsRu: 'Я',
    capsShiftEn: 'z',
    capsShiftRu: 'я',
  },
  {
    code: 'KeyX',
    caseDown: 'x',
    caseUp: 'X',
    caseDownRu: 'ч',
    caseUpRu: 'Ч',
    capsEn: 'X',
    capsRu: 'Ч',
    capsShiftEn: 'x',
    capsShiftRu: 'ч',
  },
  {
    code: 'KeyC',
    caseDown: 'c',
    caseUp: 'C',
    caseDownRu: 'с',
    caseUpRu: 'С',
    capsEn: 'C',
    capsRu: 'С',
    capsShiftEn: 'c',
    capsShiftRu: 'с',
  },
  {
    code: 'KeyV',
    caseDown: 'v',
    caseUp: 'V',
    caseDownRu: 'м',
    caseUpRu: 'М',
    capsEn: 'V',
    capsRu: 'М',
    capsShiftEn: 'v',
    capsShiftRu: 'м',
  },
  {
    code: 'KeyB',
    caseDown: 'b',
    caseUp: 'B',
    caseDownRu: 'и',
    caseUpRu: 'И',
    capsEn: 'B',
    capsRu: 'И',
    capsShiftEn: 'b',
    capsShiftRu: 'и',
  },
  {
    code: 'KeyN',
    caseDown: 'n',
    caseUp: 'N',
    caseDownRu: 'т',
    caseUpRu: 'Т',
    capsEn: 'N',
    capsRu: 'Т',
    capsShiftEn: 'n',
    capsShiftRu: 'т',
  },
  {
    code: 'KeyM',
    caseDown: 'm',
    caseUp: 'M',
    caseDownRu: 'ь',
    caseUpRu: 'Ь',
    capsEn: 'M',
    capsRu: 'Ь',
    capsShiftEn: 'm',
    capsShiftRu: 'ь',
  },
  {
    code: 'Comma',
    caseDown: ',',
    caseUp: '<',
    caseDownRu: 'б',
    caseUpRu: 'Б',
    capsEn: ',',
    capsRu: 'Б',
    capsShiftEn: '<',
    capsShiftRu: 'б',
  },
  {
    code: 'Period',
    caseDown: '.',
    caseUp: '>',
    caseDownRu: 'ю',
    caseUpRu: 'Ю',
    capsEn: '.',
    capsRu: 'Ю',
    capsShiftEn: '>',
    capsShiftRu: 'ю',
  },
  {
    code: 'Slash',
    caseDown: '/',
    caseUp: '?',
    caseDownRu: '.',
    caseUpRu: ',',
    capsEn: '/',
    capsRu: '.',
    capsShiftEn: '?',
    capsShiftRu: ',',
  },
  {
    code: 'ArrowUp',
    caseDown: '▲',
    caseUp: '▲',
    caseDownRu: '▲',
    caseUpRu: '▲',
    capsEn: '▲',
    capsRu: '▲',
    capsShiftEn: '▲',
    capsShiftRu: '▲',
  },
  {
    code: 'ShiftRight',
    caseDown: 'Shift',
    caseUp: 'Shift',
    caseDownRu: 'Shift',
    caseUpRu: 'Shift',
    capsEn: 'Shift',
    capsRu: 'Shift',
    capsShiftEn: 'Shift',
    capsShiftRu: 'Shift',
  },
];

export const FIFTH_ROW = [
  {
    code: 'ControlLeft',
    caseDown: 'Ctrl',
    caseUp: 'Ctrl',
    caseDownRu: 'Ctrl',
    caseUpRu: 'Ctrl',
    capsEn: 'Ctrl',
    capsRu: 'Ctrl',
    capsShiftEn: 'Ctrl',
    capsShiftRu: 'Ctrl',
  },
  {
    code: 'MetaLeft',
    caseDown: 'Win',
    caseUp: 'Win',
    caseDownRu: 'Win',
    caseUpRu: 'Win',
    capsEn: 'Win',
    capsRu: 'Win',
    capsShiftEn: 'Win',
    capsShiftRu: 'Win',
  },
  {
    code: 'AltLeft',
    caseDown: 'Alt',
    caseUp: 'Alt',
    caseDownRu: 'Alt',
    caseUpRu: 'Alt',
    capsEn: 'Alt',
    capsRu: 'Alt',
    capsShiftEn: 'Alt',
    capsShiftRu: 'Alt',
  },
  {
    code: 'Space',
    caseDown: '',
    caseUp: '',
    caseDownRu: '',
    caseUpRu: '',
    capsEn: '',
    capsRu: '',
    capsShiftEn: '',
    capsShiftRu: '',
  },
  {
    code: 'AltRight',
    caseDown: 'Alt',
    caseUp: 'Alt',
    caseDownRu: 'Alt',
    caseUpRu: 'Alt',
    capsEn: 'Alt',
    capsRu: 'Alt',
    capsShiftEn: 'Alt',
    capsShiftRu: 'Alt',
  },
  {
    code: 'ArrowLeft',
    caseDown: '◄',
    caseUp: '◄',
    caseDownRu: '◄',
    caseUpRu: '◄',
    capsEn: '◄',
    capsRu: '◄',
    capsShiftEn: '◄',
    capsShiftRu: '◄',
  },
  {
    code: 'ArrowDown',
    caseDown: '▼',
    caseUp: '▼',
    caseDownRu: '▼',
    caseUpRu: '▼',
    capsEn: '▼',
    capsRu: '▼',
    capsShiftEn: '▼',
    capsShiftRu: '▼',
  },
  {
    code: 'ArrowRight',
    caseDown: '►',
    caseUp: '►',
    caseDownRu: '►',
    caseUpRu: '►',
    capsEn: '►',
    capsRu: '►',
    capsShiftEn: '►',
    capsShiftRu: '►',
  },
  {
    code: 'ControlRight',
    caseDown: 'Ctrl',
    caseUp: 'Ctrl',
    caseDownRu: 'Ctrl',
    caseUpRu: 'Ctrl',
    capsEn: 'Ctrl',
    capsRu: 'Ctrl',
    capsShiftEn: 'Ctrl',
    capsShiftRu: 'Ctrl',
  },
];
