export const FIRST_ROW = [
  {
    code: "Backquote",
    caseDown: "`",
    caseUp: "~",
    caseDownRu: "ё",
    caseUpRu: "Ё",
  },
  {
    code: "Digit1",
    caseDown: "1",
    caseUp: "!",
    caseDownRu: "1",
    caseUpRu: "!",
  },
  {
    code: "Digit2",
    caseDown: "2",
    caseUp: "@",
    caseDownRu: "2",
    caseUpRu: "@",
  },
  {
    code: "Digit3",
    caseDown: "3",
    caseUp: "#",
    caseDownRu: "3",
    caseUpRu: "#",
  },
  {
    code: "Digit4",
    caseDown: "4",
    caseUp: "$",
    caseDownRu: "4",
    caseUpRu: "$",
  },
  {
    code: "Digit5",
    caseDown: "5",
    caseUp: "%",
    caseDownRu: "5",
    caseUpRu: "%",
  },
  {
    code: "Digit6",
    caseDown: "6",
    caseUp: "^",
    caseDownRu: "6",
    caseUpRu: "^",
  },
  {
    code: "Digit7",
    caseDown: "7",
    caseUp: "&",
    caseDownRu: "7",
    caseUpRu: "&",
  },
  {
    code: "Digit8",
    caseDown: "8",
    caseUp: "*",
    caseDownRu: "8",
    caseUpRu: "*",
  },
  {
    code: "Digit9",
    caseDown: "9",
    caseUp: "(",
    caseDownRu: "9",
    caseUpRu: "(",
  },
  {
    code: "Digit0",
    caseDown: "0",
    caseUp: ")",
    caseDownRu: "0",
    caseUpRu: ")",
  },
  {
    code: "Minus",
    caseDown: "-",
    caseUp: "_",
    caseDownRu: "-",
    caseUpRu: "_",
  },
  {
    code: "Equal",
    caseDown: "=",
    caseUp: "+",
    caseDownRu: "=",
    caseUpRu: "+",
  },
  {
    code: "Backspace",
    caseDown: "Backspace",
    caseUp: "Backspace",
    caseDownRu: "Backspace",
    caseUpRu: "Backspace",
  },
];

export const SECOND_ROW = [
  {
    code: "Tab",
    caseDown: "Tab",
    caseUp: "Tab",
    caseDownRu: "Tab",
    caseUpRu: "Tab",
  },
  {
    code: "KeyQ",
    caseDown: "q",
    caseUp: "Q",
    caseDownRu: "й",
    caseUpRu: "Й",
  },
  {
    code: "KeyW",
    caseDown: "w",
    caseUp: "W",
    caseDownRu: "ц",
    caseUpRu: "Ц",
  },
  {
    code: "KeyE",
    caseDown: "e",
    caseUp: "E",
    caseDownRu: "у",
    caseUpRu: "У",
  },
  {
    code: "KeyR",
    caseDown: "r",
    caseUp: "R",
    caseDownRu: "к",
    caseUpRu: "К",
  },
  {
    code: "KeyT",
    caseDown: "t",
    caseUp: "T",
    caseDownRu: "е",
    caseUpRu: "Е",
  },
  {
    code: "KeyY",
    caseDown: "y",
    caseUp: "Y",
    caseDownRu: "н",
    caseUpRu: "Н",
  },
  {
    code: "KeyU",
    caseDown: "u",
    caseUp: "U",
    caseDownRu: "г",
    caseUpRu: "Г",
  },
  {
    code: "KeyI",
    caseDown: "i",
    caseUp: "I",
    caseDownRu: "ш",
    caseUpRu: "Ш",
  },
  {
    code: "KeyO",
    caseDown: "o",
    caseUp: "O",
    caseDownRu: "щ",
    caseUpRu: "Щ",
  },
  {
    code: "KeyP",
    caseDown: "p",
    caseUp: "P",
    caseDownRu: "з",
    caseUpRu: "З",
  },
  {
    code: "BracketLeft",
    caseDown: "[",
    caseUp: "{",
    caseDownRu: "х",
    caseUpRu: "Х",
  },
  {
    code: "BracketRight",
    caseDown: "]",
    caseUp: "}",
    caseDownRu: "ъ",
    caseUpRu: "Ъ",
  },
  {
    code: "Backslash",
    caseDown: "\\",
    caseUp: "|",
    caseDownRu: "\\",
    caseUpRu: "|",
  },
  {
    code: "Delete",
    caseDown: "Del",
    caseUp: "Del",
    caseDownRu: "Del",
    caseUpRu: "Del",
  },
];

export const THIRD_ROW = [
  {
    code: "CapsLock",
    caseDown: "CapsLock",
    caseDownRu: "CapsLock",
    caseUp: "CapsLock",
    caseUpRu: "CapsLock",
  },
  {
    code: "KeyA",
    caseDown: "a",
    caseUp: "A",
    caseDownRu: "ф",
    caseUpRu: "Ф",
  },
  {
    code: "KeyS",
    caseDown: "s",
    caseUp: "S",
    caseDownRu: "ы",
    caseUpRu: "Ы",
  },
  {
    code: "KeyD",
    caseDown: "d",
    caseUp: "D",
    caseDownRu: "в",
    caseUpRu: "В",
  },
  {
    code: "KeyF",
    caseDown: "f",
    caseUp: "F",
    caseDownRu: "а",
    caseUpRu: "А",
  },
  {
    code: "KeyG",
    caseDown: "g",
    caseUp: "G",
    caseDownRu: "п",
    caseUpRu: "П",
  },
  {
    code: "KeyH",
    caseDown: "h",
    caseUp: "H",
    caseDownRu: "р",
    caseUpRu: "Р",
  },
  {
    code: "KeyJ",
    caseDown: "j",
    caseUp: "J",
    caseDownRu: "о",
    caseUpRu: "О",
  },
  {
    code: "KeyK",
    caseDown: "k",
    caseUp: "K",
    caseDownRu: "л",
    caseUpRu: "Л",
  },
  {
    code: "KeyL",
    caseDown: "l",
    caseUp: "L",
    caseDownRu: "д",
    caseUpRu: "Д",
  },
  {
    code: "Semicolon",
    caseDown: ";",
    caseUp: ":",
    caseDownRu: "ж",
    caseUpRu: "Ж",
  },
  {
    code: "Quote",
    caseDown: "'",
    caseUp: "\"",
    caseDownRu: "э",
    caseUpRu: "Э",
  },
  {
    code: "Enter",
    caseDown: "Enter",
    caseUp: "Enter",
    caseDownRu: "Enter",
    caseUpRu: "Enter",
  },
];

export const FOURTH_ROW = [
  {
    code: "ShiftLeft",
    caseDown: "Shift",
    caseUp: "Shift",
    caseDownRu: "Shift",
    caseUpRu: "Shift",
  },
  {
    code: "KeyZ",
    caseDown: "z",
    caseUp: "Z",
    caseDownRu: "я",
    caseUpRu: "Я",
  },
  {
    code: "KeyX",
    caseDown: "x",
    caseUp: "X",
    caseDownRu: "ч",
    caseUpRu: "Ч",
  },
  {
    code: "KeyC",
    caseDown: "c",
    caseUp: "C",
    caseDownRu: "с",
    caseUpRu: "С",
  },
  {
    code: "KeyV",
    caseDown: "v",
    caseUp: "V",
    caseDownRu: "м",
    caseUpRu: "М",
  },
  {
    code: "KeyB",
    caseDown: "b",
    caseUp: "B",
    caseDownRu: "и",
    caseUpRu: "И",
  },
  {
    code: "KeyN",
    caseDown: "n",
    caseUp: "N",
    caseDownRu: "т",
    caseUpRu: "Т",
  },
  {
    code: "KeyM",
    caseDown: "m",
    caseUp: "M",
    caseDownRu: "ь",
    caseUpRu: "Ь",
  },
  {
    code: "Comma",
    caseDown: ",",
    caseUp: "<",
    caseDownRu: "б",
    caseUpRu: "Б",
  },
  {
    code: "Period",
    caseDown: ".",
    caseUp: ">",
    caseDownRu: "ю",
    caseUpRu: "Ю",
  },
  {
    code: "Slash",
    caseDown: "/",
    caseUp: "?",
    caseDownRu: ".",
    caseUpRu: ",",
  },
  {
    code: "ArrowUp",
    caseDown: "▲",
    caseUp: "▲",
    caseDownRu: "▲",
    caseUpRu: "▲",
  },
  {
    code: "ShiftRight",
    caseDown: "Shift",
    caseUp: "Shift",
    caseDownRu: "Shift",
    caseUpRu: "Shift",
  },
];

export const FIFTH_ROW = [
  {
    code: "ControlLeft",
    caseDown: "Ctrl",
    caseUp: "Ctrl",
    caseDownRu: "Ctrl",
    caseUpRu: "Ctrl",
  },
  {
    code: "MetaLeft",
    caseDown: "Win",
    caseUp: "Win",
    caseDownRu: "Win",
    caseUpRu: "Win",
  },
  {
    code: "AltLeft",
    caseDown: "Alt",
    caseUp: "Alt",
    caseDownRu: "Alt",
    caseUpRu: "Alt",
  },
  {
    code: "Space",
    caseDown: "",
    caseUp: "",
    caseDownRu: "",
    caseUpRu: "",
  },
  {
    code: "AltRight",
    caseDown: "Alt",
    caseUp: "Alt",
    caseDownRu: "Alt",
    caseUpRu: "Alt",
  },
  {
    code: "ArrowLeft",
    caseDown: "◄",
    caseUp: "◄",
    caseDownRu: "◄",
    caseUpRu: "◄",
  },
  {
    code: "ArrowDown",
    caseDown: "▼",
    caseUp: "▼",
    caseDownRu: "▼",
    caseUpRu: "▼",
  },
  {
    code: "ArrowRight",
    caseDown: "►",
    caseUp: "►",
    caseDownRu: "►",
    caseUpRu: "►",
  },
  {
    code: "ControlRight",
    caseDown: "Ctrl",
    caseUp: "Ctrl",
    caseDownRu: "Ctrl",
    caseUpRu: "Ctrl",
  },
];
